# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e21fae540f931e42ec6c7dd702e04753ebd46216a8fce7ca8dfed70136c4e47cc7033212071a6a2db9948b6edfa29310cb16cf5e7fb463e305c4e615c63699ae

test:
  secret_key_base: 5bad484cd21f500737185730a0ed23f09263057101dd58005bc690d45f576bc0c58a86704db665bc9be68bcbbff5c5d21a93dfe6587f6ddca1d1d8043bc8a944

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
